# Pandas
## Pandas 란 
- 데이터 처리를 위한 라이브러리
- Wes MaKinney (월스트리트 금융분석 전문가)가 개발
- https://pandas.pydata.org/docs/index.html

- 핵심내용은 2차원 (행X열) 데이터를 핸들링 하여 효율적으로 가공/분석
    - 1) Series - column이 하나
    - 2) DataFrame - column이 여러개, Series의 집합체, 2차원 (행X열) 데이터를 담은 데이터 구조체

- 리스트, 컬렉션, 넘파이 등의 파이썬 내부 데이터뿐만 아니라 CSV 등의 파일을 쉽게 DataFrame으로 변경
- 편리하게 데이터 가공/분석

## 1. 라이브러리 불러오기

In [1]:
import pandas as pd

# 2. Pandas 의 데이터 타입
## 1) Series
- 1차원 배열 
- 배열의 인덱스(index)와 값(values)으로 구성
- 생성시에는 index=, **data=**로 설정
- 조회시에는 sr.index, **sr.values**로 사용

# data는 반드시 설정해야함. 인덱스는 생략가능

pd.Series(data=[17000, 18000, 1000, 5000])

In [2]:
pd.Series(data=[17000, 18000, 1000, 5000])

0    17000
1    18000
2     1000
3     5000
dtype: int64

- index를 설정하지 않았으므로 임의의 값인 0,1,2,3으로 나옴

pd.Series(index=[17000, 18000, 1900, 2000],
          data=["피자", "치킨","콜라", "맥주"])

In [3]:
pd.Series(index=[17000, 18000, 1900, 2000],
          data=["피자", "치킨","콜라", "맥주"])

17000    피자
18000    치킨
1900     콜라
2000     맥주
dtype: object

- 'data='은 생략가능

sr = pd.Series([17000, 18000, 1000, 5000])

In [4]:
sr = pd.Series([17000, 18000, 1000, 5000])

sr = pd.Series([17000, 18000, 1000, 5000],
               index=["피자", "치킨", "콜라", "맥주"])

In [5]:
sr = pd.Series([17000, 18000, 1000, 5000],
               index=["피자", "치킨", "콜라", "맥주"])

## 2) Dataframe

- 행과 열을 가지는 2차원 자료구조
- 행방향 이름: index 
- 열방향 이름: column

- 생성시에는 index=, columns=, **data=** 로 설정
- 조회시에는 df.index, df.columns=, **df.value**로 사용

In [6]:
index = ['one', 'two', 'three']
columns = ['A', 'B', 'C']
values = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

df = pd.DataFrame(data=values, index=index, columns=columns)
df

In [7]:
df = pd.DataFrame(data=values, index=index, columns=columns)
df

       A  B  C
one    1  2  3
two    4  5  6
three  7  8  9

- 생성된 데이터프레임으로부터 인덱스(index), 열(columns), 값(values)을 각각 출력해 보면..

df.index
df.columns
df.values

In [8]:
df.index

Index(['one', 'two', 'three'], dtype='object')

In [9]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [10]:
df.values

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int64)

# 3. DataFrame 의 생성
- DataFrame은 리스트(List), 시리즈(Series), 딕셔너리(dict), Numpy의 ndarray, csv로부터 생성할 수 있음
- pd.DataFrame()

## 1) 딕셔너리로부터 데이터프레임 생성 - {'key' : [value]}
- key: columns
- value: value
- index: 기본값

data = {
    '학번' : ['1000', '1001'],
    '이름' : [ 'Steve', 'James'],
    '점수': [90.72, 78.09]
    }

In [15]:
data = {
    '학번' : ['1000', '1001'],
    '이름' : [ 'Steve', 'James'],
    '점수': [90.72, 78.09]
    }

pd.DataFrame(data)

In [16]:
pd.DataFrame(data)

     학번     이름     점수
0  1000  Steve  90.72
1  1001  James  78.09

## 2) 외부 파일로 부터 데이터프레임 생성
- Pandas는 CSV, 텍스트, Excel, SQL, HTML, JSON 등 다양한 데이터 파일을 읽어 데이터 프레임을 생성할 수 있음
- pd.read_csv()

# 파일 로딩
lemonade = pd.read_csv('lemonade.csv')

In [17]:
lemonade = pd.read_csv('lemonade.csv')

In [19]:
lemonade

         Date Location  Lemon  Orange  Temperature  Leaflets  Price
0    7/1/2016     Park     97      67           70      90.0   0.25
1    7/2/2016     Park     98      67           72      90.0   0.25
2    7/3/2016     Park    110      77           71     104.0   0.25
3    7/4/2016    Beach    134      99           76      98.0   0.25
4    7/5/2016    Beach    159     118           78     135.0   0.25
5    7/6/2016    Beach    103      69           82      90.0   0.25
6    7/6/2016    Beach    103      69           82      90.0   0.25
7    7/7/2016    Beach    143     101           81     135.0   0.25
8         NaN    Beach    123      86           82     113.0   0.25
9    7/9/2016    Beach    134      95           80     126.0   0.25
10  7/10/2016    Beach    140      98           82     131.0   0.25
11  7/11/2016    Beach    162     120           83     135.0   0.25
12  7/12/2016    Beach    130      95           84      99.0   0.25
13  7/13/2016    Beach    109      75           77      99.0   0.25
14  7/14/2016    Beach    122      85           78     113.0   0.25
15  7/15/2016    Beach     98      62           75     108.0   0.50
16  7/16/2016    Beach     81      50           74      90.0   0.50
17  7/17/2016    Beach    115      76           77     126.0   0.50
18  7/18/2016     Park    131      92           81     122.0   0.50
19  7/19/2016     Park    122      85           78     113.0   0.50
20  7/20/2016     Park     71      42           70       NaN   0.50
21  7/21/2016     Park     83      50           77      90.0   0.50
22  7/22/2016     Park    112      75           80     108.0   0.50
23  7/23/2016     Park    120      82           81     117.0   0.50
24  7/24/2016     Park    121      82           82     117.0   0.50
25  7/25/2016     Park    156     113           84     135.0   0.50
26  7/26/2016     Park    176     129           83     158.0   0.35
27  7/27/2016     Park    104      68           80      99.0   0.35
28  7/28/2016     Park     96      63           82      90.0   0.35
29  7/29/2016     Park    100      66           81      95.0   0.35
30  7/30/2016    Beach     88      57           82      81.0   0.35
31  7/31/2016    Beach     76      47           82      68.0   0.35

이 경우 인덱스는 자동으로 부여됨

In [20]:
print(lemonade.index)

RangeIndex(start=0, stop=32, step=1)